### ISSUE TITLE
Develop icons for integrations

### ISSUE THREAD

**Issue by akhursevich** [zebrunner/reporting-ui#50]
<img width="1454" alt="Screen Shot 2019-05-13 at 11 09 54 AM" src="https://user-images.githubusercontent.com/1182755/57605805-263f9980-7570-11e9-8235-c749b12ec2ff.png">

**Comment by vabramova** [comment]
[Integrations_svg.zip](https://github.com/qaprosoft/zafira-ui/files/3177309/Integrations_svg.zip)

**Comment by vabramova** [comment]
[Integrations_zafira_svg.zip](https://github.com/qaprosoft/zafira-ui/files/3182443/Integrations_zafira_svg.zip)

**Comment by vabramova** [comment]
DESKTOP 
zpl://project?pid=5acb41c5487a27ab9f0560a1&tags=Integrations

**Comment by vabramova** [comment]
MOBILE
zpl://project?pid=5acb41c5487a27ab9f0560a1&tags=Integration_mobile
