### ISSUE TITLE
Emty company logo should have different icon

### ISSUE THREAD

**Issue by akhursevich** [zebrunner/reporting-ui#55]
<img width="115" alt="Screen Shot 2019-05-14 at 12 53 01 AM" src="https://user-images.githubusercontent.com/1182755/57657045-cd5d1900-75e2-11e9-8693-e895359982c4.png">
 
Use reference:
zpl://screen?sid=5cc0341e59871e53b36dd8cb&pid=5acb41c5487a27ab9f0560a1

**Comment by danymill** [comment]
Solved
