### ISSUE TITLE
Tune design of toasts

### ISSUE THREAD

**Issue by akhursevich** [zebrunner/reporting-ui#78]
Currently, they are looking not so good and evident:
<img width="554" alt="Screen Shot 2019-05-16 at 7 07 58 PM" src="https://user-images.githubusercontent.com/1182755/57869666-31175a00-780e-11e9-8ecf-498ff66b1f87.png">
<img width="426" alt="Screen Shot 2019-05-16 at 7 08 36 PM" src="https://user-images.githubusercontent.com/1182755/57869668-32488700-780e-11e9-9202-014808f85567.png">

**Comment by vabramova** [comment]
zpl://screen?pid=5acb41c5487a27ab9f0560a1&sid=5cac5c9d300c1ba055072dba
